# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"
# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "rose_pine"

# Starship modules
[character]
# Note the use of Catppuccin color 'peach'
success_symbol = "[[ó°„›](sky) â¯](peach)"
error_symbol = "[[ó°„›](red) â¯](peach)"
vimcmd_symbol = "[ó°„› â®](subtext1)"  # For use with zsh-vi-mode

[git_branch]
symbol = "ï˜ "
style = "bold mauve"

[directory]
truncation_length = 4
read_only = " ó°Œ¾"
style = "bold lavender"

[bun]
format = "via [$symbol]($style)"
symbol = "î¯ "

[buf]
format = "via [$symbol]($style)"
symbol = "ï’ "

[cmake]
format = "via [$symbol]($style)"
symbol = "î” "

[cobol]
format = "via [$symbol]($style)"

[crystal]
format = "via [$symbol]($style)"
symbol = "î˜¯ "

[daml]
format = "via [$symbol]($style)"

[dart]
format = "via [$symbol]($style)"
symbol = "î˜ "

[deno]
format = "via [$symbol]($style)"
symbol = "îŸ€ "

[dotnet]
format = "[$symbol(ğŸ¯ $tfm )]($style)"

[elixir]
format = "via [$symbol]($style)"
symbol = "î˜­ "

[elm]
format = "via [$symbol]($style)"
symbol = "î˜¬ "

[erlang]
format = "via [$symbol]($style)"

[fennel]
format = "via [$symbol]($style)"
symbol = "îš¯ "

[gleam]
format = "via [$symbol]($style)"

[golang]
format = "via [$symbol]($style)"
symbol = "î˜§ "

[gradle]
format = "via [$symbol]($style)"
symbol = "î™  "

[haxe]
format = "via [$symbol]($style)"
symbol = "î™¦ "

[helm]
format = "via [$symbol]($style)"

[java]
format = "via [$symbol]($style)"
symbol = "î‰– "

[julia]
format = "via [$symbol]($style)"
symbol = "î˜¤ "

[kotlin]
format = "via [$symbol]($style)"
symbol = "î˜´ "

[lua]
format = "via [$symbol]($style)"
symbol = "î˜  "

[meson]
format = "via [$symbol]($style)"
symbol = "ó°”· "

[nim]
format = "via [$symbol]($style)"
symbol = "ó°†¥ "

[nodejs]
format = "via [$symbol]($style)"
symbol = "îœ˜ "

[ocaml]
format = 'via [$symbol(\($switch_indicator$switch_name\) )]($style)'
symbol = "î™º "

[opa]
format = "via [$symbol]($style)"

[perl]
format = "via [$symbol]($style)"
symbol = "î™¾ "

[pixi]
format = "via [$symbol($environment )]($style)"
symbol = "ó°— "

[php]
format = "via [$symbol]($style)"
symbol = "î˜ˆ "

[pulumi]
format = "via [$symbol$stack]($style)"

[purescript]
format = "via [$symbol]($style)"

[python]
format = "via [$symbol]($style)"
symbol = "îˆµ "

[quarto]
format = "via [$symbol]($style)"

[raku]
format = "via [$symbol]($style)"

[red]
format = "via [$symbol]($style)"

[rlang]
format = "via [$symbol]($style)"
symbol = "ó°Ÿ” "

[ruby]
format = "via [$symbol]($style)"
symbol = "î‘ "

[rust]
format = "via [$symbol]($style)"
symbol = "ó±˜— "

[solidity]
format = "via [$symbol]($style)"

[typst]
format = "via [$symbol]($style)"

[swift]
format = "via [$symbol]($style)"
symbol = "î• "

[vagrant]
format = "via [$symbol]($style)"

[vlang]
format = "via [$symbol]($style)"

[zig]
format = "via [$symbol]($style)"
symbol = "îš© "

[aws]
symbol = "îŒ½ "

[c]
symbol = "î˜ "

[cpp]
symbol = "î˜ "

[conda]
symbol = "ï„Œ "

[docker_context]
symbol = "ïŒˆ "

[fossil_branch]
symbol = "ï˜ "

[gcloud]
symbol = "îŒ½ "
disabled = true

[git_commit]
tag_symbol = " ï’ "

[guix_shell]
symbol = "ïŒ¥ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[hostname]
ssh_symbol = "î¬ "

[memory_usage]
symbol = "ó°› "

[nix_shell]
symbol = "ïŒ“ "

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CachyOS = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "

[package]
symbol = "ó°— "

[pijul_channel]
symbol = "ï˜ "

[scala]
symbol = "îœ· "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.tokyo_night]
bg = "#1a1b26"
bg_dark = "#16161e"
bg_highlight = "#292e42"
terminal_black = "#414868"
fg = "#c0caf5"
fg_dark = "#a9b1d6"
fg_gutter = "#3b4261"
dark3 = "#545c7e"
comment = "#565f89"
dark5 = "#737aa2"
blue0 = "#3d59a1"
blue = "#7aa2f7"
cyan = "#7dcfff"
blue1 = "#2ac3de"
blue2 = "#0db9d7"
blue5 = "#89ddff"
blue6 = "#B4F9F8"
blue7 = "#394b70"
magenta = "#bb9af7"
magenta2 = "#ff007c"
purple = "#9d7cd8"
orange = "#ff9e64"
yellow = "#e0af68"
green = "#9ece6a"
green1 = "#73daca"
green2 = "#41a6b5"
teal = "#1abc9c"
red = "#f7768e"
red1 = "#db4b4b"

[palettes.rose_pine]
rosewater = "#ebbcba"
flamingo  = "#f0c6c6"
pink      = "#f2d5cf"
mauve     = "#c4a7e7"
red       = "#eb6f92"
maroon    = "#b4637a"
peach     = "#f6c177"
yellow    = "#f6c177"
green     = "#31748f"
teal      = "#9ccfd8"
sky       = "#9ccfd8"
sapphire  = "#31748f"
blue      = "#9ccfd8"
lavender  = "#c4a7e7"

text      = "#e0def4"
subtext1  = "#c5c3d9"
subtext0  = "#a9a7bb"

overlay2  = "#6e6a86"
overlay1  = "#56526e"
overlay0  = "#44415a"

surface2  = "#393552"
surface1  = "#2a273f"
surface0  = "#26233a"

base      = "#1f1d2e"
mantle    = "#1b1926"
crust     = "#171520"
